DROP DATABASE IF EXISTS SystemVault;

CREATE DATABASE IF NOT EXISTS SystemVault;
USE SystemVault;

CREATE TABLE User (
	Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(50) NOT NULL,
    Password TEXT NOT NULL
);

CREATE TABLE Category (
	Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL
);

CREATE TABLE ServiceFile (
	Id BIGINT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Path TEXT NOT NULL,
    Size BIGINT NOT NULL,
    CreatedAt DATETIME NOT NULL,
    CategoryId BIGINT,
    FOREIGN KEY (CategoryId) REFERENCES Category(Id)
);